org.gradle.jvmargs=-Xmx4G
android.useAndroidX=true
android.enableJetifier=true
# Set this locally or in CI. It is a Mapbox secret download token, not the public map token.
# MAPBOX_DOWNLOADS_TOKEN=
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
